import type { SGProperty } from './models';

/**
 * Illustrative sample coordinates, psf and lease data for demo purposes — not sourced from
 * HDB/URA records. A real build should pull this from URA's REALIS/OneMap API or user-entered
 * address geocoding, and psf from actual caveat transactions rather than hand-authored numbers.
 * Districts follow Singapore's standard 28 postal-district groupings (see DISTRICT_INFO).
 */
export const PROPERTIES: SGProperty[] = [
  {
    id: 'dawson-queenstown',
    name: 'Dawson Road, Queenstown',
    type: 'hdb',
    town: 'Queenstown',
    district: 3,
    tenure: { type: 'leasehold99', leaseStartYear: 2015 },
    location: { lat: 1.2967, lon: 103.8034 },
    indicativePrice: 780_000,
  },
  {
    id: 'bishan-st-near-aitong',
    name: 'Bishan Street 22',
    type: 'hdb',
    town: 'Bishan',
    district: 20,
    tenure: { type: 'leasehold99', leaseStartYear: 1990 },
    location: { lat: 1.3506, lon: 103.83 },
    indicativePrice: 650_000,
  },
  {
    id: 'serangoon-north-hdb',
    name: 'Serangoon North Avenue 1',
    type: 'hdb',
    town: 'Serangoon North',
    district: 19,
    tenure: { type: 'leasehold99', leaseStartYear: 1985 },
    location: { lat: 1.362, lon: 103.872 },
    indicativePrice: 550_000,
  },
  {
    id: 'bukit-timah-landed',
    name: 'Bukit Timah Terrace House',
    type: 'landed',
    town: 'Bukit Timah',
    district: 10,
    tenure: { type: 'freehold' },
    location: { lat: 1.32, lon: 103.805 },
    indicativePrice: 3_800_000,
  },
  {
    id: 'trilinq-clementi',
    name: 'The Trilinq, Clementi',
    type: 'condo',
    town: 'Clementi',
    district: 5,
    tenure: { type: 'leasehold99', leaseStartYear: 2014 },
    location: { lat: 1.314, lon: 103.7649 },
    pricePsfHistoric: 1450,
    unitSizeSqft: 1050,
    mcstFeeMonthly: 380,
    facilities: 'full',
    indicativePrice: 1_522_500,
  },
  {
    id: 'marine-parade-condo',
    name: 'Marine Parade Freehold Condo',
    type: 'condo',
    town: 'Marine Parade',
    district: 15,
    tenure: { type: 'freehold' },
    location: { lat: 1.302, lon: 103.905 },
    pricePsfHistoric: 2100,
    unitSizeSqft: 950,
    mcstFeeMonthly: 550,
    facilities: 'premium',
    indicativePrice: 1_995_000,
  },
  {
    id: 'sky-habitat-bishan',
    name: 'Sky Habitat, Bishan',
    type: 'condo',
    town: 'Bishan',
    district: 20,
    tenure: { type: 'leasehold99', leaseStartYear: 2015 },
    location: { lat: 1.3555, lon: 103.848 },
    pricePsfHistoric: 1750,
    unitSizeSqft: 1100,
    mcstFeeMonthly: 480,
    facilities: 'premium',
    indicativePrice: 1_925_000,
  },
  {
    id: 'trevista-toa-payoh',
    name: 'Trevista, Toa Payoh',
    type: 'condo',
    town: 'Toa Payoh',
    district: 12,
    tenure: { type: 'leasehold99', leaseStartYear: 2012 },
    location: { lat: 1.3345, lon: 103.847 },
    pricePsfHistoric: 1550,
    unitSizeSqft: 900,
    mcstFeeMonthly: 350,
    facilities: 'full',
    indicativePrice: 1_395_000,
  },
  {
    id: 'clement-canopy-clementi',
    name: 'The Clement Canopy, Clementi',
    type: 'condo',
    town: 'Clementi',
    district: 5,
    tenure: { type: 'leasehold99', leaseStartYear: 2017 },
    location: { lat: 1.333, lon: 103.7745 },
    pricePsfHistoric: 1650,
    unitSizeSqft: 980,
    mcstFeeMonthly: 400,
    facilities: 'full',
    indicativePrice: 1_617_000,
  },
  {
    id: 'parc-riviera-west-coast',
    name: 'Parc Riviera, West Coast',
    type: 'condo',
    town: 'West Coast',
    district: 5,
    tenure: { type: 'leasehold99', leaseStartYear: 2016 },
    location: { lat: 1.3115, lon: 103.7645 },
    pricePsfHistoric: 1350,
    unitSizeSqft: 1150,
    mcstFeeMonthly: 280,
    facilities: 'basic',
    indicativePrice: 1_552_500,
  },
  {
    id: 'garden-residences-serangoon',
    name: 'The Garden Residences, Serangoon',
    type: 'condo',
    town: 'Serangoon North',
    district: 19,
    tenure: { type: 'leasehold99', leaseStartYear: 2018 },
    location: { lat: 1.358, lon: 103.8695 },
    pricePsfHistoric: 1500,
    unitSizeSqft: 1020,
    mcstFeeMonthly: 360,
    facilities: 'full',
    indicativePrice: 1_530_000,
  },
  {
    id: 'tampines-grande',
    name: 'Tampines Grande',
    type: 'condo',
    town: 'Tampines',
    district: 18,
    tenure: { type: 'leasehold99', leaseStartYear: 2013 },
    location: { lat: 1.347, lon: 103.935 },
    pricePsfHistoric: 1250,
    unitSizeSqft: 1100,
    mcstFeeMonthly: 250,
    facilities: 'basic',
    indicativePrice: 1_375_000,
  },
  {
    id: 'nim-collection-novena',
    name: 'Nim Collection, Novena',
    type: 'condo',
    town: 'Novena',
    district: 11,
    tenure: { type: 'freehold' },
    location: { lat: 1.3255, lon: 103.84 },
    pricePsfHistoric: 2300,
    unitSizeSqft: 850,
    mcstFeeMonthly: 600,
    facilities: 'premium',
    indicativePrice: 1_955_000,
  },
  {
    id: 'marina-one-residences',
    name: 'Marina One Residences',
    type: 'condo',
    town: 'Marina',
    district: 1,
    tenure: { type: 'leasehold99', leaseStartYear: 2017 },
    location: { lat: 1.2807, lon: 103.8535 },
    pricePsfHistoric: 2600,
    unitSizeSqft: 800,
    mcstFeeMonthly: 650,
    facilities: 'premium',
    indicativePrice: 2_080_000,
  },
  {
    id: 'icon-tanjong-pagar',
    name: 'Icon, Tanjong Pagar',
    type: 'condo',
    town: 'Tanjong Pagar',
    district: 2,
    tenure: { type: 'leasehold99', leaseStartYear: 2007 },
    location: { lat: 1.2762, lon: 103.844 },
    pricePsfHistoric: 2200,
    unitSizeSqft: 750,
    mcstFeeMonthly: 500,
    facilities: 'full',
    indicativePrice: 1_650_000,
  },
  {
    id: 'harbourfront-suites',
    name: 'HarbourFront Suites',
    type: 'condo',
    town: 'Telok Blangah',
    district: 4,
    tenure: { type: 'leasehold99', leaseStartYear: 2011 },
    location: { lat: 1.2653, lon: 103.8221 },
    pricePsfHistoric: 1800,
    unitSizeSqft: 850,
    mcstFeeMonthly: 420,
    facilities: 'full',
    indicativePrice: 1_530_000,
  },
  {
    id: 'city-square-residences',
    name: 'City Square Residences',
    type: 'condo',
    town: 'Little India',
    district: 8,
    tenure: { type: 'leasehold99', leaseStartYear: 2009 },
    location: { lat: 1.3123, lon: 103.8547 },
    pricePsfHistoric: 1700,
    unitSizeSqft: 900,
    mcstFeeMonthly: 400,
    facilities: 'full',
    indicativePrice: 1_530_000,
  },
  {
    id: 'sixth-avenue-residences',
    name: 'Sixth Avenue Residences',
    type: 'condo',
    town: 'Bukit Timah',
    district: 10,
    tenure: { type: 'leasehold99', leaseStartYear: 2021 },
    location: { lat: 1.3225, lon: 103.7969 },
    pricePsfHistoric: 2400,
    unitSizeSqft: 950,
    mcstFeeMonthly: 550,
    facilities: 'premium',
    indicativePrice: 2_280_000,
  },
  {
    id: 'beauty-world-residences',
    name: 'Beauty World Residences',
    type: 'condo',
    town: 'Beauty World',
    district: 21,
    tenure: { type: 'leasehold99', leaseStartYear: 2023 },
    location: { lat: 1.3411, lon: 103.7759 },
    pricePsfHistoric: 2100,
    unitSizeSqft: 900,
    mcstFeeMonthly: 480,
    facilities: 'premium',
    indicativePrice: 1_890_000,
  },
  {
    id: 'daintree-residence',
    name: 'Daintree Residence',
    type: 'condo',
    town: 'Toh Tuck / Bukit Timah',
    district: 21,
    tenure: { type: 'leasehold99', leaseStartYear: 2021 },
    location: { lat: 1.339, lon: 103.783 },
    pricePsfHistoric: 1750,
    unitSizeSqft: 1000,
    mcstFeeMonthly: 420,
    facilities: 'full',
    indicativePrice: 1_750_000,
  },
  {
    id: 'braddell-view-hdb',
    name: 'Braddell View',
    type: 'hdb',
    town: 'Macpherson',
    district: 13,
    tenure: { type: 'leasehold99', leaseStartYear: 1978 },
    location: { lat: 1.339, lon: 103.862 },
    indicativePrice: 480_000,
  },
  {
    id: 'paya-lebar-quarter',
    name: 'Paya Lebar Quarter',
    type: 'condo',
    town: 'Paya Lebar',
    district: 14,
    tenure: { type: 'leasehold99', leaseStartYear: 2019 },
    location: { lat: 1.318, lon: 103.8925 },
    pricePsfHistoric: 1900,
    unitSizeSqft: 850,
    mcstFeeMonthly: 450,
    facilities: 'full',
    indicativePrice: 1_615_000,
  },
  {
    id: 'bedok-north-hdb',
    name: 'Bedok North Avenue 2',
    type: 'hdb',
    town: 'Bedok',
    district: 16,
    tenure: { type: 'leasehold99', leaseStartYear: 1995 },
    location: { lat: 1.33, lon: 103.94 },
    indicativePrice: 560_000,
  },
  {
    id: 'jurong-west-hdb',
    name: 'Jurong West Street 42',
    type: 'hdb',
    town: 'Jurong West',
    district: 22,
    tenure: { type: 'leasehold99', leaseStartYear: 1988 },
    location: { lat: 1.34, lon: 103.705 },
    indicativePrice: 480_000,
  },
  {
    id: 'le-quest-bukit-batok',
    name: 'Le Quest, Bukit Batok',
    type: 'condo',
    town: 'Bukit Batok',
    district: 23,
    tenure: { type: 'leasehold99', leaseStartYear: 2017 },
    location: { lat: 1.3496, lon: 103.749 },
    pricePsfHistoric: 1450,
    unitSizeSqft: 1000,
    mcstFeeMonthly: 350,
    facilities: 'full',
    indicativePrice: 1_450_000,
  },
  {
    id: 'woodlands-hdb',
    name: 'Woodlands Drive 16',
    type: 'hdb',
    town: 'Woodlands',
    district: 25,
    tenure: { type: 'leasehold99', leaseStartYear: 1998 },
    location: { lat: 1.436, lon: 103.786 },
    indicativePrice: 460_000,
  },
  {
    id: 'yishun-hdb',
    name: 'Yishun Ring Road',
    type: 'hdb',
    town: 'Yishun',
    district: 27,
    tenure: { type: 'leasehold99', leaseStartYear: 1992 },
    location: { lat: 1.4295, lon: 103.835 },
    indicativePrice: 430_000,
  },
  {
    id: 'punggol-waterway-condo',
    name: 'Punggol Waterway Terraces',
    type: 'condo',
    town: 'Punggol',
    district: 19,
    tenure: { type: 'leasehold99', leaseStartYear: 2019 },
    location: { lat: 1.4032, lon: 103.9021 },
    pricePsfHistoric: 1400,
    unitSizeSqft: 950,
    mcstFeeMonthly: 320,
    facilities: 'full',
    indicativePrice: 1_330_000,
  },
];

export function propertyById(id: string): SGProperty | undefined {
  return PROPERTIES.find((p) => p.id === id);
}

/**
 * Average historic psf among sample condos in the same district — a rough "is this psf typical"
 * reference point. With a bigger dataset this would be a real transaction-based comparable.
 */
export function averagePsf(district: number): number | undefined {
  const psfs = PROPERTIES.filter((p) => p.type === 'condo' && p.district === district && p.pricePsfHistoric != null).map(
    (p) => p.pricePsfHistoric as number
  );
  if (psfs.length === 0) return undefined;
  return Math.round(psfs.reduce((a, b) => a + b, 0) / psfs.length);
}

/**
 * Average indicative price for a property type in a district, for HDB/landed where there's
 * no psf figure to compare — same sample-data caveat as averagePsf.
 */
export function averageIndicativePrice(type: SGProperty['type'], district: number): number | undefined {
  const prices = PROPERTIES.filter((p) => p.type === type && p.district === district).map((p) => p.indicativePrice);
  if (prices.length === 0) return undefined;
  return Math.round(prices.reduce((a, b) => a + b, 0) / prices.length);
}
